import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatGbp, formatGbpOrPoa, formatUkDate } from "@/lib/format";
import { sumCostings } from "@/lib/pricing";
import type { AppSettings, Costing, Grn, GrnItem, Part, Supplier, Workpack } from "@/types";
import { activityService } from "@/services/activityService";

export async function downloadGrnPdf(input: {
  settings: AppSettings;
  grn: Grn;
  supplier: Supplier | null;
  workpack: Workpack | null;
  items: GrnItem[];
  parts: Part[];
  costings: Costing[];
}) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(27, 54, 93);
  doc.rect(0, 0, pageWidth, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text(input.settings.companyName, 14, 12);
  doc.setFontSize(10);
  doc.text("Goods Received / Costing Sheet", 14, 20);
  doc.text(input.grn.grnNumber, pageWidth - 14, 12, { align: "right" });
  doc.text(formatUkDate(input.grn.date), pageWidth - 14, 20, { align: "right" });

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(10);
  const meta = [
    ["Supplier", input.supplier?.name ?? "—"],
    ["Invoice", input.grn.invoice || "—"],
    ["Tracking", input.grn.supplierTrackingReference || "—"],
    ["Batch", input.grn.supplierBatchNumber || "—"],
    ["Workpack", input.workpack?.workpackNumber ?? "—"],
    ["Registration", input.grn.registration || input.workpack?.registration || "—"],
    ["Sheet", `${input.grn.sheetNumber} of ${input.grn.totalSheets}`],
    ["Status", input.grn.status],
  ];
  autoTable(doc, {
    startY: 34,
    theme: "plain",
    styles: { fontSize: 9, cellPadding: 1.4 },
    columnStyles: { 0: { fontStyle: "bold", cellWidth: 32 }, 1: { cellWidth: 60 }, 2: { fontStyle: "bold", cellWidth: 32 }, 3: { cellWidth: 60 } },
    body: [
      [meta[0][0], meta[0][1], meta[1][0], meta[1][1]],
      [meta[2][0], meta[2][1], meta[3][0], meta[3][1]],
      [meta[4][0], meta[4][1], meta[5][0], meta[5][1]],
      [meta[6][0], meta[6][1], meta[7][0], meta[7][1]],
    ],
  });

  const partMap = new Map(input.parts.map((part) => [part.id, part]));
  const costingMap = new Map(input.costings.map((row) => [row.grnItemId, row]));
  autoTable(doc, {
    startY: (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY
      ? ((doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable!.finalY + 6)
      : 70,
    head: [["P/N", "Description", "Qty", "Sale Price EA", "Total Sale"]],
    body: input.items.map((item) => {
      const part = partMap.get(item.partId);
      const costing = costingMap.get(item.id);
      const isPoa = costing?.pricingMethod === "POA";
      return [
        part?.partNumber ?? "—",
        item.description,
        String(item.quantity),
        formatGbpOrPoa(costing?.salePriceEa, isPoa),
        formatGbpOrPoa(costing?.totalSale, isPoa),
      ];
    }),
    styles: { fontSize: 8.5, cellPadding: 2 },
    headStyles: { fillColor: [27, 54, 93], textColor: 255 },
    columnStyles: {
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
    },
  });

  const totals = sumCostings(input.costings);
  const finalY =
    (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 180;
  doc.setFontSize(10);
  doc.text(`Total Sale: ${totals.totalSale === null ? "POA / mixed" : formatGbp(totals.totalSale)}`, pageWidth - 14, finalY + 10, {
    align: "right",
  });
  doc.text(`Total Cost: ${formatGbp(totals.totalCost)}`, pageWidth - 14, finalY + 16, { align: "right" });
  doc.text(
    `Profit: ${totals.profit === null ? "POA / Not calculated" : formatGbp(totals.profit)}`,
    pageWidth - 14,
    finalY + 22,
    { align: "right" },
  );
  if (input.grn.notes) {
    doc.setFontSize(9);
    doc.text(`Notes: ${input.grn.notes}`, 14, finalY + 32);
  }
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Generated by Ash Aviation Stores inventory system", 14, 287);
  doc.save(`${input.grn.grnNumber}.pdf`);
  await activityService.log({
    action: "report_generated",
    entityType: "grn",
    entityId: input.grn.id,
    reference: input.grn.grnNumber,
    description: `Downloaded PDF for ${input.grn.grnNumber}`,
  });
}
